@startumlactor Testcasecreate "ips : IncreasePointsStrategy" as ipsTestcase -> ips: new IncreasePointsStrategy(point : int)create "sjs : ScoreJokerStrategy" as sjsTestcase -> sjs: new ScoreJokerStrategy(ips)create "j : Joker" as jTestcase -> j: new Joker(nombre, descripcion , sjs)create "raj : RandomApplyJoker" as rajTestcase -> raj: new RandomApplyJoker(random : int, j)create "s :Score" as sTestcase -> s: new Score(10, 1, 0)Testcase -> raj: apply(s)raj -> j: apply(s)j -> sjs: apply(s)sjs -> ips: apply(s)ips -> s: increasePoints(point)@enduml