@startumlactor Testcasecreate "ips : IncreasePointsStrategy" as ipsTestcase -> ips: new IncreasePointsStrategy(point : int)create "mms : MultiplyMultStrategy" as mmsTestcase -> mms: new MultiplyMultStrategy(mult)create "op : OnePair" as opTestcase -> op: new OnePair()create "s :Score" as sop -> s: new Score(10, 2, 0)create "t : Tarot" as tTestcase -> t: new Tarot(nombre, descripcion , List<ips, mms>, op)Testcase -> t: use()t -> op: applyTarot(t)op -> t: apply(s)loop Por cada ScoringStrategy   t -> ips: apply(s)  ips -> s: increasePoints(point)  note right of ips : Analogo para MultiplyMultStrategyend loop@enduml